### ISSUE TITLE
There is no path-param function mentioned in the README

### ISSUE THREAD

**Issue by joshcho** [jeko2000/tiny-routes#7]

**Comment by nathanvy** [comment]
This issue is pretty poorly-explained, but what I think @joshcho is getting at is that the readme mentions a `path-param` selector function in the [usage](https://github.com/jeko2000/tiny-routes/blob/develop/README.org#usage) section, but the function is not defined within `tiny-routes`.

It would be great to have that function exported by `tiny-routes` if only to save users from reinventing the wheel.

**Comment by bgutter** [comment]
This tripped me up too. I thought I had loaded the system incorrectly or something.

**Comment by jeko2000** [comment]
Thank you @joshcho, @nathanvy, and @bgutter for reporting.
The latest patch adds a `path-parameter` function, a `with-path-parameters` macro, adds relevant unit tests, and updates the README accordingly.
